sudo: true

language: cpp

os:
 - linux
# - osx

compiler:
 - clang
 - gcc

before_script:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libpng12-0 libpng12-dev; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libeigen3-dev; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libavformat-dev libavcodec-dev libavutil-dev; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install opencl-headers fglrx; fi

script:
 - mkdir build
 - cd build
 - cmake .. && make
