sudo: true

language: cpp

os:
 - linux
# - osx

notifications:
 email: false

compiler:
 - clang
 - gcc

before_script:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libpng12-0 libpng12-dev; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libeigen3-dev; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libavformat-dev libavcodec-dev libavutil-dev; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install opencl-headers; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      sudo ln -s ${AMDAPPSDK}/lib/x86_64/libamdocl64.so /usr/lib/libOpenCL.so;
   fi;

script:
 - mkdir build
 - cd build
 - cmake .. && make
